# Generated by Django 4.0 on 2021-12-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField(auto_created=True, auto_now_add=True)),
                ('Date', models.DateField(auto_created=True, auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, upload_to='uploaded/')),
                ('Is_Liked', models.BooleanField(default=False)),
            ],
        ),
    ]
